FROM node:22-alpine
# берем Node.js для запуска React/Vite

WORKDIR /app

COPY package*.json ./

RUN npm ci
# устанавливаем зависимости из package*.json

COPY . .

EXPOSE 5173
# порт Vite

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]